import os
import re
import tkinter as tk
from pathlib import Path
from tkinter import filedialog

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

# ==========================================================
# Parent folder containing all series folders
# ==========================================================
root = tk.Tk()
root.withdraw()

parent_folder = Path(filedialog.askdirectory())

print("User selected:", parent_folder)

# ==========================================================
# Randomization distance settings
# ==========================================================
# Random points are generated by:
#   1. choosing a random skeleton coordinate
#   2. choosing a random 3D direction
#   3. choosing a random radius between MIN_DISTANCE_UM and MAX_DISTANCE_UM
#   4. placing the point at that offset from the selected skeleton coordinate
#
# Examples:
#   MIN_DISTANCE_UM = 0.0
#   MAX_DISTANCE_UM = 5.0
#     -> points are placed 0 to 5 um away from the chosen skeleton coordinate
#
#   MIN_DISTANCE_UM = 5.0
#   MAX_DISTANCE_UM = 5.0
#     -> points are placed exactly 5 um away from the chosen skeleton coordinate
#
# Note:
#   By default, the distance range is measured relative to the chosen skeleton
#   coordinate, preserving the behavior of your original script.
#
#   If ENFORCE_NEAREST_SKELETON_RANGE = True, the script also checks the nearest
#   skeleton coordinate after generation and rejects points outside the range.
#   This can be slower, especially for narrow or exact ranges like 5.0-5.0.
# ==========================================================
MIN_DISTANCE_UM = 0.0
MAX_DISTANCE_UM = 5.0

ENFORCE_NEAREST_SKELETON_RANGE = False
NEAREST_RANGE_TOLERANCE_UM = 1e-6
MAX_REJECTION_ATTEMPTS_PER_POINT = 10000

RANDOM_SEED = None  # Set to an integer for reproducible random points.

# ==========================================================
# Plot settings
# ==========================================================
HIST_BINS = 50

MRNA_COLORS = {
    "MS2": "purple",
    "ATP2": "red",
    "ATP3": "red",
    "TIM50": "red",
}

# ==========================================================
# File/folder naming
# ==========================================================
SPOT_COUNT_PATTERNS = [
    "*_spot_counts.csv",
    "*_spot_counts.xlsx",
    "*_counts.csv",
    "*_counts.xlsx",
]

GENERATED_FOLDER_KEYWORDS = {
    "converted_coordinates",
    "random_ms2_output",
    "random_atp2_output",
    "random_atp3_output",
    "random_tim50_output",
    "random_output",
    "randomized_mrna_output",
    "mito_visualization_interactive",
}

EXCLUDE_FILENAME_KEYWORDS = [
    "nn_distance",
    "random",
    "distribution",
    "run_summary",
    "per_cell_summary",
    "converted",
    "xyz_um",
    "no_nn",
]


# ==========================================================
# Utility functions
# ==========================================================
def sanitize_name(name):
    name = str(name).strip()
    if name == "":
        name = "mRNA"
    for bad in ["\\", "/", ":", "*", "?", '"', "<", ">", "|"]:
        name = name.replace(bad, "_")
    name = re.sub(r"\s+", "_", name)
    return name


def format_distance_value(value):
    """
    Format a distance value for Windows-safe folder/file names.
    """
    value = float(value)
    text = f"{value:g}"
    text = text.replace("-", "neg").replace(".", "p")
    return text


def make_distance_range_tag():
    """
    Create a compact label such as dist_0p0_to_5p0um or dist_5_to_5um.
    """
    return (
        f"dist_{format_distance_value(MIN_DISTANCE_UM)}"
        f"_to_{format_distance_value(MAX_DISTANCE_UM)}um"
    )


def validate_distance_settings():
    if MIN_DISTANCE_UM < 0:
        raise ValueError("MIN_DISTANCE_UM must be >= 0.")
    if MAX_DISTANCE_UM < 0:
        raise ValueError("MAX_DISTANCE_UM must be >= 0.")
    if MIN_DISTANCE_UM > MAX_DISTANCE_UM:
        raise ValueError("MIN_DISTANCE_UM must be <= MAX_DISTANCE_UM.")
    if MAX_REJECTION_ATTEMPTS_PER_POINT < 1:
        raise ValueError("MAX_REJECTION_ATTEMPTS_PER_POINT must be >= 1.")


def normalize_stem(name):
    """
    Normalize filenames for matching cell names to skeleton txt files.
    """
    s = Path(str(name)).stem.lower()

    # Remove common generated suffixes/prefixes.
    s = s.replace("_xyz_um", "")
    s = s.replace("_random", "")
    s = s.replace("spots_extractions_", "")
    s = s.replace("spots_extraction_", "")

    # Normalize separators and remove non-alphanumeric chars.
    s = re.sub(r"[^a-z0-9]+", "", s)
    return s


def extract_cell_index(name):
    """
    Extract trailing cell index such as 000, 001, 017 from a filename.
    This is used as a fallback match when long filenames differ by mRNA folder.
    """
    stem = Path(str(name)).stem
    m = re.search(r"[_\-](\d{1,4})$", stem)
    if m:
        return int(m.group(1))
    return None


def make_short_cell_label(cell_name):
    """
    Create a short, Windows-safe output filename.

    The prior version used the entire source filename, which can exceed the
    Windows MAX_PATH limit when nested inside ATP2/MS2 results folders.
    """
    cell_i = extract_cell_index(cell_name)
    if cell_i is not None:
        return f"cell_{cell_i:03d}"

    # Fallback to a truncated sanitized name.
    stem = sanitize_name(Path(str(cell_name)).stem)
    if len(stem) > 40:
        stem = stem[-40:]
    return stem


def infer_mrna_name(path):
    known_names = ["MS2", "ATP2", "ATP3", "TIM50"]

    pieces = list(Path(path).parts)
    pieces.append(Path(path).name)

    for part in reversed(pieces):
        upper = part.upper()
        for name in known_names:
            if re.search(rf"(^|[_\-\s]){re.escape(name)}([_\-\s]|$)", upper):
                return name

    stem = Path(path).stem
    stem = re.sub(r"(_spot_counts|_counts)$", "", stem, flags=re.IGNORECASE)
    return sanitize_name(stem)


def is_inside_generated_folder(path):
    lower_parts = {p.lower() for p in Path(path).parts}
    return any(k in lower_parts for k in GENERATED_FOLDER_KEYWORDS)


def looks_like_candidate_count_file(path):
    name = path.name.lower()

    if path.name.startswith("~$"):
        return False

    if is_inside_generated_folder(path):
        return False

    # Must have one of these intended suffixes.
    if not (
        name.endswith("_spot_counts.csv")
        or name.endswith("_spot_counts.xlsx")
        or name.endswith("_counts.csv")
        or name.endswith("_counts.xlsx")
    ):
        return False

    # Exclude generated/non-input files.
    for keyword in EXCLUDE_FILENAME_KEYWORDS:
        if (
            keyword in name
            and "spot_counts" not in name
            and not name.endswith("_counts.csv")
            and not name.endswith("_counts.xlsx")
        ):
            return False

    return True


def find_count_files(parent):
    found = []
    for pattern in SPOT_COUNT_PATTERNS:
        found.extend(parent.rglob(pattern))

    filtered = [p for p in found if looks_like_candidate_count_file(p)]
    return sorted(set(filtered))


def read_raw_table(count_file):
    suffix = count_file.suffix.lower()

    if suffix == ".csv":
        for kwargs in [
            {},
            {"sep": None, "engine": "python"},
            {"sep": "\t"},
        ]:
            try:
                df = pd.read_csv(count_file, **kwargs)
                if df.shape[1] > 0:
                    return df
            except Exception:
                pass
        raise ValueError("Could not read CSV file.")

    if suffix in [".xlsx", ".xlsm", ".xls"]:
        return pd.read_excel(count_file)

    raise ValueError(f"Unsupported count table type: {count_file}")


def read_count_table(count_file):
    df = read_raw_table(count_file)
    df.columns = [str(c).strip() for c in df.columns]

    if df.shape[1] < 2:
        raise ValueError(
            f"Not a count table: only {df.shape[1]} column(s). "
            f"Columns found: {list(df.columns)}"
        )

    filename_col = None
    count_col = None

    for candidate in [
        "Filename",
        "filename",
        "FileName",
        "file",
        "Cell",
        "cell",
        "cell_name",
        "CellName",
        "RelativeInputPath",
    ]:
        if candidate in df.columns:
            filename_col = candidate
            break

    for candidate in [
        "SpotCount",
        "spot_count",
        "Spot Count",
        "Count",
        "count",
        "mRNA_count",
        "mrna_count",
        "mRNACount",
    ]:
        if candidate in df.columns:
            count_col = candidate
            break

    # Fallback: choose first text-like column for filename and first numeric-like column for count.
    if filename_col is None or count_col is None:
        possible_filename_cols = []
        possible_count_cols = []

        for col in df.columns:
            series = df[col].dropna()

            if len(series) == 0:
                continue

            numeric = pd.to_numeric(series, errors="coerce")
            numeric_fraction = numeric.notna().mean()

            if numeric_fraction > 0.8:
                possible_count_cols.append(col)
            else:
                possible_filename_cols.append(col)

        if filename_col is None and possible_filename_cols:
            filename_col = possible_filename_cols[0]

        if count_col is None and possible_count_cols:
            for col in possible_count_cols:
                if col != filename_col:
                    count_col = col
                    break

    if filename_col is None or count_col is None:
        filename_col = df.columns[0]
        count_col = df.columns[1]

    out = df[[filename_col, count_col]].copy()
    out.columns = ["cell_name", "mrna_count"]

    out = out.dropna(subset=["cell_name", "mrna_count"])
    out["mrna_count"] = pd.to_numeric(out["mrna_count"], errors="coerce")
    out = out.dropna(subset=["mrna_count"])
    out["mrna_count"] = out["mrna_count"].astype(int)

    if len(out) == 0:
        raise ValueError(
            "No valid filename/count rows after parsing. "
            f"Columns found: {list(df.columns)}"
        )

    return out


def find_series_folder(path):
    p = Path(path)
    for ancestor in p.parents:
        if ancestor.name.lower().startswith("series"):
            return ancestor
    return p.parent


def find_cells_folders_in_series(series_folder):
    return [
        p
        for p in series_folder.rglob("*")
        if p.is_dir()
        and p.name.lower() == "cells"
        and not is_inside_generated_folder(p)
    ]


def load_skeleton_txt(path):
    """
    Load a MitoGraph skeleton txt file and return x/y/z coordinates.
    """
    read_attempts = [
        {"sep": "\t"},
        {"sep": None, "engine": "python"},
        {"sep": r"\s+", "engine": "python"},
    ]

    last_error = None

    for kwargs in read_attempts:
        try:
            df = pd.read_csv(path, **kwargs)
            df.columns = [str(c).strip() for c in df.columns]

            if {"x", "y", "z"}.issubset(df.columns):
                xyz = df[["x", "y", "z"]].dropna().values.astype(float)
                xyz = xyz[np.isfinite(xyz).all(axis=1)]

                if len(xyz) > 0:
                    return xyz

        except Exception as e:
            last_error = e

    raise ValueError(
        f"Could not read valid x/y/z columns from skeleton file. Last error: {last_error}"
    )


def is_valid_skeleton_txt(path):
    """
    Only accept txt files that can actually be loaded as MitoGraph skeletons.
    This prevents accidental matching to logs or notes.
    """
    try:
        xyz = load_skeleton_txt(path)
        return len(xyz) > 0
    except Exception:
        return False


def build_shared_series_skeleton_index(series_folder):
    """
    Build one skeleton index for an entire Series folder.

    Both MS2 and ATP2 count files in the same Series use the same shared skeleton
    files from the Series/cells folder(s), instead of searching separately inside
    each mRNA-specific branch.
    """
    search_roots = find_cells_folders_in_series(series_folder)

    # If no cells folders exist, search the whole series as fallback.
    if len(search_roots) == 0:
        search_roots = [series_folder]

    txt_files = []
    for root in search_roots:
        txt_files.extend(root.rglob("*.txt"))

    index = {}
    index_by_cell_number = {}
    valid_files = []
    rejected_files = []

    for p in txt_files:
        if is_inside_generated_folder(p):
            continue

        name_lower = p.name.lower()

        if "no_nn_distances" in name_lower:
            continue
        if "summary" in name_lower:
            continue
        if "random" in name_lower:
            continue

        if not is_valid_skeleton_txt(p):
            rejected_files.append(p)
            continue

        key = normalize_stem(p.name)
        if key == "":
            continue

        valid_files.append(p)

        # Exact normalized-key index.
        if key not in index:
            index[key] = p

        # Fallback index by trailing cell number.
        cell_i = extract_cell_index(p.name)
        if cell_i is not None and cell_i not in index_by_cell_number:
            index_by_cell_number[cell_i] = p

    return {
        "series_folder": series_folder,
        "search_roots": search_roots,
        "index": index,
        "index_by_cell_number": index_by_cell_number,
        "valid_files": valid_files,
        "rejected_files": rejected_files,
    }


def find_matching_skeleton(cell_name, skeleton_bundle):
    """
    Match a count-table cell name to a shared series skeleton txt file.
    """
    skeleton_index = skeleton_bundle["index"]
    by_number = skeleton_bundle["index_by_cell_number"]

    key = normalize_stem(cell_name)

    # Exact normalized stem match.
    if key in skeleton_index:
        return skeleton_index[key]

    # Add .txt variant.
    key_txt = normalize_stem(f"{cell_name}.txt")
    if key_txt in skeleton_index:
        return skeleton_index[key_txt]

    # Partial matching fallback.
    candidates = []
    for skel_key, path in skeleton_index.items():
        if key and (key in skel_key or skel_key in key):
            candidates.append(path)

    if len(candidates) == 1:
        return candidates[0]

    if len(candidates) > 1:
        # Prefer shortest filename difference.
        candidates = sorted(
            candidates, key=lambda p: abs(len(normalize_stem(p.name)) - len(key))
        )
        return candidates[0]

    # Fallback by trailing cell number, e.g. _000, _001.
    cell_i = extract_cell_index(cell_name)
    if cell_i is not None and cell_i in by_number:
        return by_number[cell_i]

    return None


def random_unit_vector():
    direction = np.random.normal(size=3)
    norm = np.linalg.norm(direction)

    if norm == 0:
        return np.array([1.0, 0.0, 0.0])

    return direction / norm


def point_is_inside_distance_range(point, skeleton_tree):
    """
    Optional nearest-skeleton validation.

    This checks the nearest skeleton coordinate, not the nearest continuous
    skeleton segment.
    """
    nearest_distance, _ = skeleton_tree.query(point, k=1)

    low_ok = nearest_distance >= (MIN_DISTANCE_UM - NEAREST_RANGE_TOLERANCE_UM)
    high_ok = nearest_distance <= (MAX_DISTANCE_UM + NEAREST_RANGE_TOLERANCE_UM)

    return low_ok and high_ok


def generate_random_points_near_skeleton(
    xyz,
    n_points,
    min_distance,
    max_distance,
    enforce_nearest_skeleton_range=False,
):
    """
    Generate random points around MitoGraph skeleton coordinates.

    Parameters
    ----------
    xyz : ndarray, shape (n, 3)
        Skeleton x/y/z coordinates in microns.
    n_points : int
        Number of random mRNA points to create.
    min_distance : float
        Minimum offset distance in microns from the chosen skeleton coordinate.
    max_distance : float
        Maximum offset distance in microns from the chosen skeleton coordinate.
    enforce_nearest_skeleton_range : bool
        If False, only the offset from the chosen skeleton coordinate is controlled.
        If True, the point is accepted only if its nearest skeleton coordinate is
        also within [MIN_DISTANCE_UM, MAX_DISTANCE_UM].
    """
    if n_points <= 0:
        return np.empty((0, 3), dtype=float)

    if min_distance < 0:
        raise ValueError("min_distance must be >= 0.")
    if max_distance < 0:
        raise ValueError("max_distance must be >= 0.")
    if min_distance > max_distance:
        raise ValueError("min_distance must be <= max_distance.")

    generated = []
    skeleton_tree = cKDTree(xyz) if enforce_nearest_skeleton_range else None

    for point_i in range(int(n_points)):
        accepted = False

        for attempt_i in range(MAX_REJECTION_ATTEMPTS_PER_POINT):
            idx = np.random.randint(len(xyz))
            base = xyz[idx]

            direction = random_unit_vector()
            radius = np.random.uniform(min_distance, max_distance)
            pt = base + radius * direction

            if not enforce_nearest_skeleton_range:
                generated.append(pt)
                accepted = True
                break

            if point_is_inside_distance_range(pt, skeleton_tree):
                generated.append(pt)
                accepted = True
                break

        if not accepted:
            raise RuntimeError(
                "Could not generate a random point within the requested nearest-skeleton "
                f"distance range after {MAX_REJECTION_ATTEMPTS_PER_POINT} attempts. "
                "Try widening the distance range, increasing NEAREST_RANGE_TOLERANCE_UM, "
                "or setting ENFORCE_NEAREST_SKELETON_RANGE = False."
            )

    return np.array(generated, dtype=float)


def analyze_count_file(count_file, skeleton_bundle):
    mrna = sanitize_name(infer_mrna_name(count_file))
    distance_tag = make_distance_range_tag()

    out_folder = count_file.parent / f"random_{mrna}_output_{distance_tag}"
    out_folder.mkdir(parents=True, exist_ok=True)

    print(f"\nProcessing count table: {count_file}")
    print(f"  mRNA/channel name: {mrna}")
    print(f"  Distance range: {MIN_DISTANCE_UM} to {MAX_DISTANCE_UM} um")
    print(f"  Enforce nearest-skeleton range: {ENFORCE_NEAREST_SKELETON_RANGE}")
    print(f"  Shared Series skeleton folder: {skeleton_bundle['series_folder']}")
    print(f"  Valid shared skeleton txt files: {len(skeleton_bundle['valid_files'])}")
    print(f"  Output folder: {out_folder}")

    count_df = read_count_table(count_file)
    print(f"  Count rows: {len(count_df)}")

    if len(skeleton_bundle["valid_files"]) == 0:
        print(
            "  No valid shared MitoGraph skeleton txt files found. Skipping this count table."
        )
        return {
            "count_file": str(count_file),
            "mrna": mrna,
            "distance_min_um": MIN_DISTANCE_UM,
            "distance_max_um": MAX_DISTANCE_UM,
            "enforce_nearest_skeleton_range": ENFORCE_NEAREST_SKELETON_RANGE,
            "status": "no_valid_shared_skeleton_txt_files_found",
            "rows": len(count_df),
            "valid_shared_skeleton_files": 0,
            "matched_cells": 0,
            "missing_or_error_cells": len(count_df),
            "generated_points": 0,
            "nn_distances": 0,
            "output_folder": str(out_folder),
        }

    all_nn = []
    per_cell_summary = []

    matched_cells = 0
    missing_cells = 0
    generated_points_total = 0

    for _, row in count_df.iterrows():
        cell_name = str(row["cell_name"])
        n_mrna = int(row["mrna_count"])

        skeleton_path = find_matching_skeleton(cell_name, skeleton_bundle)

        if skeleton_path is None:
            missing_cells += 1
            print(f"  Missing shared skeleton for: {cell_name}")
            per_cell_summary.append(
                {
                    "mRNA": mrna,
                    "CellName": cell_name,
                    "mRNACount": n_mrna,
                    "DistanceMinUM": MIN_DISTANCE_UM,
                    "DistanceMaxUM": MAX_DISTANCE_UM,
                    "EnforceNearestSkeletonRange": ENFORCE_NEAREST_SKELETON_RANGE,
                    "SkeletonFile": "",
                    "Status": "missing_shared_skeleton",
                    "RandomCoordinateFile": "",
                    "NNDistancesInCell": 0,
                }
            )
            continue

        try:
            xyz = load_skeleton_txt(skeleton_path)
            generated = generate_random_points_near_skeleton(
                xyz=xyz,
                n_points=n_mrna,
                min_distance=MIN_DISTANCE_UM,
                max_distance=MAX_DISTANCE_UM,
                enforce_nearest_skeleton_range=ENFORCE_NEAREST_SKELETON_RANGE,
            )

            generated_points_total += len(generated)

            random_name = make_short_cell_label(cell_name)
            random_csv = out_folder / f"{random_name}_random_{mrna}_{distance_tag}.csv"
            random_csv.parent.mkdir(parents=True, exist_ok=True)

            pd.DataFrame(generated, columns=["x", "y", "z"]).to_csv(
                random_csv, index=False
            )

            nn_count = 0
            if len(generated) > 1:
                tree = cKDTree(generated)
                d, _ = tree.query(generated, k=2)
                nn = d[:, 1]
                all_nn.extend(nn)
                nn_count = len(nn)

            matched_cells += 1

            per_cell_summary.append(
                {
                    "mRNA": mrna,
                    "CellName": cell_name,
                    "mRNACount": n_mrna,
                    "DistanceMinUM": MIN_DISTANCE_UM,
                    "DistanceMaxUM": MAX_DISTANCE_UM,
                    "EnforceNearestSkeletonRange": ENFORCE_NEAREST_SKELETON_RANGE,
                    "SkeletonFile": str(skeleton_path),
                    "Status": "processed",
                    "RandomCoordinateFile": str(random_csv),
                    "NNDistancesInCell": nn_count,
                }
            )

            print(
                f"  {cell_name}: count={n_mrna}, shared skeleton={skeleton_path.name}"
            )

        except Exception as e:
            missing_cells += 1
            print(f"  Error processing {cell_name}: {e}")
            per_cell_summary.append(
                {
                    "mRNA": mrna,
                    "CellName": cell_name,
                    "mRNACount": n_mrna,
                    "DistanceMinUM": MIN_DISTANCE_UM,
                    "DistanceMaxUM": MAX_DISTANCE_UM,
                    "EnforceNearestSkeletonRange": ENFORCE_NEAREST_SKELETON_RANGE,
                    "SkeletonFile": str(skeleton_path),
                    "Status": f"error: {e}",
                    "RandomCoordinateFile": "",
                    "NNDistancesInCell": 0,
                }
            )

    all_nn = np.array(all_nn, dtype=float)

    npy_path = out_folder / f"random_{mrna}_nn_{distance_tag}.npy"
    csv_path = out_folder / f"random_{mrna}_nn_{distance_tag}.csv"

    np.save(npy_path, all_nn)

    pd.DataFrame(all_nn, columns=[f"NN_{mrna}_distance"]).to_csv(csv_path, index=False)

    per_cell_summary_path = out_folder / f"random_{mrna}_per_cell_summary_{distance_tag}.csv"
    pd.DataFrame(per_cell_summary).to_csv(per_cell_summary_path, index=False)

    plot_path = out_folder / f"random_{mrna}_distribution_{distance_tag}.png"

    if len(all_nn) > 0:
        plt.figure(figsize=(8, 6), facecolor="white")

        plt.hist(
            all_nn,
            bins=HIST_BINS,
            color=MRNA_COLORS.get(mrna.upper(), "blue"),
            edgecolor="black",
        )

        plt.xlabel("Nearest-neighbor distance (um)")
        plt.ylabel("Frequency")
        plt.title(
            f"Random {mrna} All Cells | "
            f"{MIN_DISTANCE_UM:g}-{MAX_DISTANCE_UM:g} um from skeleton"
        )

        plt.tight_layout()
        plt.savefig(plot_path, dpi=300, facecolor="white", bbox_inches="tight")
        plt.close()

        print(f"  Saved plot: {plot_path}")
    else:
        note_path = out_folder / f"random_{mrna}_NO_NN_DISTANCES_{distance_tag}.txt"
        note_path.write_text(
            "No nearest-neighbor distances were calculated. "
            "This usually means no cells had more than one generated point, "
            "or no shared skeleton files were matched.\n",
            encoding="utf-8",
        )
        print("  No plot created because there were no NN distances.")

    print(f"  Saved random NN npy: {npy_path}")
    print(f"  Saved random NN csv: {csv_path}")
    print(f"  Saved per-cell summary: {per_cell_summary_path}")

    return {
        "count_file": str(count_file),
        "mrna": mrna,
        "distance_min_um": MIN_DISTANCE_UM,
        "distance_max_um": MAX_DISTANCE_UM,
        "enforce_nearest_skeleton_range": ENFORCE_NEAREST_SKELETON_RANGE,
        "status": "processed",
        "series_folder": str(skeleton_bundle["series_folder"]),
        "rows": len(count_df),
        "valid_shared_skeleton_files": len(skeleton_bundle["valid_files"]),
        "matched_cells": matched_cells,
        "missing_or_error_cells": missing_cells,
        "generated_points": generated_points_total,
        "nn_distances": len(all_nn),
        "output_folder": str(out_folder),
        "nn_csv": str(csv_path),
        "nn_npy": str(npy_path),
        "plot": str(plot_path) if len(all_nn) > 0 else "",
        "per_cell_summary": str(per_cell_summary_path),
    }


def main():
    validate_distance_settings()

    if RANDOM_SEED is not None:
        np.random.seed(RANDOM_SEED)

    if not parent_folder.exists():
        raise FileNotFoundError(f"Parent folder does not exist: {parent_folder}")

    count_files = find_count_files(parent_folder)

    print(f"Parent folder: {parent_folder}")
    print(f"Found {len(count_files)} candidate count files")
    print(f"Distance range: {MIN_DISTANCE_UM} to {MAX_DISTANCE_UM} um")
    print(f"Enforce nearest-skeleton range: {ENFORCE_NEAREST_SKELETON_RANGE}")

    if len(count_files) == 0:
        print("No count files found.")
        print("Expected names like:")
        print("  MS2_spot_counts.csv")
        print("  ATP2_spot_counts.csv")
        print("  ATP3_spot_counts.csv")
        print("  TIM50_spot_counts.csv")
        print("  ms2_counts.xlsx")
        print("  atp2_counts.xlsx")
        print("  atp3_counts.xlsx")
        print("  tim50_counts.xlsx")
        return

    # Build one shared skeleton bundle per Series folder.
    series_to_bundle = {}

    for count_file in count_files:
        series_folder = find_series_folder(count_file)
        if series_folder not in series_to_bundle:
            print(f"\nIndexing shared skeletons for series: {series_folder}")
            bundle = build_shared_series_skeleton_index(series_folder)
            series_to_bundle[series_folder] = bundle

            print(f"  Search roots:")
            for root in bundle["search_roots"]:
                print(f"    {root}")
            print(f"  Valid skeleton txt files: {len(bundle['valid_files'])}")
            print(f"  Rejected txt files: {len(bundle['rejected_files'])}")

    run_summary = []
    skipped_invalid = 0

    for count_file in count_files:
        try:
            series_folder = find_series_folder(count_file)
            skeleton_bundle = series_to_bundle[series_folder]

            result = analyze_count_file(count_file, skeleton_bundle)
            run_summary.append(result)

        except Exception as e:
            skipped_invalid += 1
            print(f"\nSkipping invalid count table: {count_file}")
            print(f"  Reason: {e}")
            run_summary.append(
                {
                    "count_file": str(count_file),
                    "mrna": infer_mrna_name(count_file),
                    "distance_min_um": MIN_DISTANCE_UM,
                    "distance_max_um": MAX_DISTANCE_UM,
                    "enforce_nearest_skeleton_range": ENFORCE_NEAREST_SKELETON_RANGE,
                    "status": f"skipped_invalid_count_table: {e}",
                    "series_folder": str(find_series_folder(count_file)),
                    "rows": "",
                    "valid_shared_skeleton_files": "",
                    "matched_cells": "",
                    "missing_or_error_cells": "",
                    "generated_points": "",
                    "nn_distances": "",
                    "output_folder": "",
                    "nn_csv": "",
                    "nn_npy": "",
                    "plot": "",
                    "per_cell_summary": "",
                }
            )

    summary_path = (
        parent_folder
        / f"random_mrna_recursive_run_summary_SHARED_SKELETON_{make_distance_range_tag()}.csv"
    )
    pd.DataFrame(run_summary).to_csv(summary_path, index=False)

    print("\nDone.")
    print(f"Candidate count files checked: {len(count_files)}")
    print(f"Invalid count files skipped: {skipped_invalid}")
    print(f"Overall run summary: {summary_path}")


if __name__ == "__main__":
    main()
