import re
import tkinter as tk
from pathlib import Path
from tkinter import filedialog

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

# ==========================================================
# mRNA colocalization analysis
# ==========================================================
# Purpose
# -------
# Compare two mRNA channels cell-by-cell within each Series folder.
#
# Example:
#   MRNA_A = "MS2"
#   MRNA_B = "ATP3"
#
# The script reads converted coordinate files generated by:
#   6.mrna_nn_distance_recursive.py
#
# Expected coordinate files:
#   Series 4/MS2/.../spots_extraction/converted_coordinates/cell_000_xyz_um.csv
#   Series 4/ATP3/.../spots_extraction/converted_coordinates/cell_000_xyz_um.csv
#
# A punctum is called "colocalized" if its nearest punctum from the other mRNA
# channel is within COLOCALIZATION_DISTANCE_UM in 3D Euclidean distance.
# ==========================================================


# ==========================================================
# Folder picker
# ==========================================================
root = tk.Tk()
root.withdraw()

parent_folder = Path(
    filedialog.askdirectory(
        title="Select parent folder containing Series folders"
    )
)

print("User selected:", parent_folder)


# ==========================================================
# User settings
# ==========================================================
# Compare these two mRNA channels.
MRNA_A = "MS2"
MRNA_B = "ATP3"

# Adjustable overlap / colocalization distance threshold in microns.
# Example values to try:
#   0.10, 0.25, 0.50, 1.00
COLOCALIZATION_DISTANCE_UM = 0.25

# Coordinate scale factors.
# If your converted_coordinates files are already in microns, keep these at 1.
A_X_SCALE_UM = 1.0
A_Y_SCALE_UM = 1.0
A_Z_SCALE_UM = 1.0

B_X_SCALE_UM = 1.0
B_Y_SCALE_UM = 1.0
B_Z_SCALE_UM = 1.0

# Only use files inside converted_coordinates folders.
# This avoids accidentally analyzing derived surface-distance tables or summaries.
PROCESS_ONLY_CONVERTED_COORDINATES = True

# Make per-cell plots. Turn off if the run is very large and you only want tables.
MAKE_PER_CELL_PLOTS = True

# Make pooled all-cell plots.
MAKE_POOLED_PLOTS = True

# Write Excel files in addition to CSV files.
WRITE_EXCEL = True

# Known mRNA names used for path inference.
KNOWN_MRNA_NAMES = ["MS2", "ATP2", "ATP3", "TIM50"]


# ==========================================================
# Output naming
# ==========================================================
OUTPUT_ROOT_NAME = "mrna_coloc_BY_SERIES"

GENERATED_FOLDER_KEYWORDS = {
    "converted_coordinates",  # excluded only from scanning roots, not input files
    "mrna_coloc_by_series",
    "node_mrna_dist_by_series",
    "node_mrna_distance_output",
    "node_mrna_distance_output_by_series",
    "mito_visualization_interactive",
    "random_ms2_output",
    "random_atp2_output",
    "random_atp3_output",
    "random_tim50_output",
    "random_output",
    "randomized_mrna_output",
    "plots",
}

DERIVED_INPUT_EXCLUDE_KEYWORDS = [
    "surface_distances",
    "global_calibration",
    "nearest_node",
    "node_occupancy",
    "summary",
    "run_summary",
    "spot_counts",
    "nn_distance",
    "distribution",
    "histogram",
    "random",
]


# ==========================================================
# Utility functions
# ==========================================================
def sanitize_name(name):
    name = str(name).strip()
    if name == "":
        name = "unnamed"

    for bad in ["\\", "/", ":", "*", "?", '"', "<", ">", "|"]:
        name = name.replace(bad, "_")

    name = re.sub(r"\s+", "_", name)
    return name


def format_distance_value(value):
    text = f"{float(value):g}"
    return text.replace("-", "neg").replace(".", "p")


def distance_tag():
    return f"{format_distance_value(COLOCALIZATION_DISTANCE_UM)}um"


def is_inside_generated_output(path):
    lower_parts = {p.lower() for p in Path(path).parts}
    generated_without_converted = {
        k for k in GENERATED_FOLDER_KEYWORDS if k != "converted_coordinates"
    }
    return any(k in lower_parts for k in generated_without_converted)


def find_series_folders(parent):
    parent = Path(parent)

    if parent.name.lower().startswith("series"):
        return [parent]

    series_folders = [
        p
        for p in parent.rglob("*")
        if p.is_dir()
        and p.name.lower().startswith("series")
        and not is_inside_generated_output(p)
    ]

    series_folders = sorted(set(series_folders))

    # Avoid duplicated analysis if nested Series folders exist.
    non_nested = []
    for series in series_folders:
        if not any(other != series and other in series.parents for other in series_folders):
            non_nested.append(series)

    if len(non_nested) == 0:
        return [parent]

    return non_nested


def make_series_label(series_folder, parent):
    series_folder = Path(series_folder)
    parent = Path(parent)

    try:
        rel = series_folder.relative_to(parent)
        return sanitize_name("__".join(rel.parts))
    except Exception:
        return sanitize_name(series_folder.name)


def extract_cell_index(name):
    stem = Path(str(name)).stem

    # Expected: cell_000_xyz_um.csv
    m = re.search(r"(?:^|[_\-])cell[_\-]?(\d{1,4})(?:[_\-]|$)", stem, flags=re.IGNORECASE)
    if m:
        return int(m.group(1))

    # Fallback: trailing _000
    m = re.search(r"[_\-](\d{1,4})$", stem)
    if m:
        return int(m.group(1))

    return None


def cell_label(cell_index):
    if cell_index is None:
        return "cell_unknown"
    return f"cell_{int(cell_index):03d}"


def infer_mrna_from_path(path, series_folder=None):
    """
    Infer the mRNA channel from the folder structure.

    Preferred structure:
      Series 4/MS2/MS2_.../results/spots_extraction/converted_coordinates/cell_000_xyz_um.csv
      Series 4/ATP3/ATP3_.../results/spots_extraction/converted_coordinates/cell_000_xyz_um.csv

    The first folder under the Series folder is usually the mRNA channel.
    """
    p = Path(path)

    if series_folder is not None:
        try:
            rel_parts = p.relative_to(series_folder).parts
            if len(rel_parts) > 0:
                first = rel_parts[0].upper()
                for name in KNOWN_MRNA_NAMES:
                    if first == name.upper():
                        return name
        except Exception:
            pass

    pieces = list(p.parts)
    pieces.append(p.name)

    for part in reversed(pieces):
        upper = part.upper()
        for name in KNOWN_MRNA_NAMES:
            if re.search(rf"(^|[_\-\s\(]){re.escape(name)}([_\-\s\)]|$)", upper):
                return name

    return "unknown"


def is_converted_coordinate_file(path):
    p = Path(path)
    name = p.name.lower()
    lower_parts = {part.lower() for part in p.parts}

    if p.name.startswith("~$"):
        return False

    if p.suffix.lower() not in [".csv", ".xlsx", ".xlsm", ".xls"]:
        return False

    if PROCESS_ONLY_CONVERTED_COORDINATES and "converted_coordinates" not in lower_parts:
        return False

    if PROCESS_ONLY_CONVERTED_COORDINATES:
        if not re.search(r"^cell[_\-]?\d{1,4}.*xyz.*um", name):
            return False

    for keyword in DERIVED_INPUT_EXCLUDE_KEYWORDS:
        if keyword in name:
            return False

    if is_inside_generated_output(p):
        return False

    return True


def find_coordinate_files(series_folder):
    files = []

    if PROCESS_ONLY_CONVERTED_COORDINATES:
        files.extend(Path(series_folder).rglob("cell_*_xyz_um.csv"))
        files.extend(Path(series_folder).rglob("cell_*_xyz_um.xlsx"))
        files.extend(Path(series_folder).rglob("cell_*_xyz_um.xlsm"))
        files.extend(Path(series_folder).rglob("cell_*_xyz_um.xls"))
    else:
        for ext in ["*.csv", "*.xlsx", "*.xlsm", "*.xls"]:
            files.extend(Path(series_folder).rglob(ext))

    return sorted(set(p for p in files if is_converted_coordinate_file(p)))


def read_table(path):
    path = Path(path)
    suffix = path.suffix.lower()

    if suffix == ".csv":
        read_attempts = [
            {},
            {"sep": ","},
            {"sep": "\t"},
            {"sep": ";"},
            {"sep": None, "engine": "python"},
        ]

        best = None
        best_cols = -1

        for kwargs in read_attempts:
            try:
                df = pd.read_csv(path, **kwargs)
                df.columns = [str(c).strip() for c in df.columns]

                if df.shape[1] > best_cols:
                    best = df
                    best_cols = df.shape[1]

                try:
                    find_xyz_columns(df)
                    return df
                except Exception:
                    pass

            except Exception:
                pass

        if best is not None:
            return best

        raise ValueError(f"Could not read CSV file: {path}")

    if suffix in [".xlsx", ".xlsm", ".xls"]:
        df = pd.read_excel(path)
        df.columns = [str(c).strip() for c in df.columns]
        return df

    raise ValueError(f"Unsupported table type: {path}")


def normalize_column_name(col):
    s = str(col).strip().lower()
    s = s.replace("µ", "u")
    s = s.replace("μ", "u")
    s = re.sub(r"[^a-z0-9]+", "", s)
    return s


def find_xyz_columns(df):
    normalized = {col: normalize_column_name(col) for col in df.columns}

    x_names = {
        "x",
        "xum",
        "xmicron",
        "xmicrons",
        "xposition",
        "positionx",
        "xpos",
        "posx",
        "centroidx",
        "centerx",
        "spotx",
        "globalx",
    }

    y_names = {
        "y",
        "yum",
        "ymicron",
        "ymicrons",
        "yposition",
        "positiony",
        "ypos",
        "posy",
        "centroidy",
        "centery",
        "spoty",
        "globaly",
    }

    z_names = {
        "z",
        "zum",
        "zmicron",
        "zmicrons",
        "zposition",
        "positionz",
        "zpos",
        "posz",
        "centroidz",
        "centerz",
        "spotz",
        "globalz",
    }

    x_col = next((col for col, norm in normalized.items() if norm in x_names), None)
    y_col = next((col for col, norm in normalized.items() if norm in y_names), None)
    z_col = next((col for col, norm in normalized.items() if norm in z_names), None)

    if x_col is not None and y_col is not None and z_col is not None:
        return x_col, y_col, z_col

    # Fallback: first three mostly numeric columns.
    numeric_cols = []
    for col in df.columns:
        series = df[col].dropna()
        if len(series) == 0:
            continue

        numeric = pd.to_numeric(series, errors="coerce")
        if numeric.notna().mean() > 0.8:
            numeric_cols.append(col)

    if len(numeric_cols) >= 3:
        return numeric_cols[0], numeric_cols[1], numeric_cols[2]

    raise ValueError(
        "Could not identify x/y/z coordinate columns. "
        f"Columns found: {list(df.columns)}"
    )


def load_coordinates(path, scale_xyz=(1.0, 1.0, 1.0)):
    df = read_table(path)
    x_col, y_col, z_col = find_xyz_columns(df)

    coords = df[[x_col, y_col, z_col]].copy()
    coords.columns = ["x", "y", "z"]

    coords["x"] = pd.to_numeric(coords["x"], errors="coerce")
    coords["y"] = pd.to_numeric(coords["y"], errors="coerce")
    coords["z"] = pd.to_numeric(coords["z"], errors="coerce")
    coords = coords.dropna(subset=["x", "y", "z"])
    coords = coords[np.isfinite(coords[["x", "y", "z"]]).all(axis=1)]

    xyz = coords[["x", "y", "z"]].to_numpy(dtype=float)

    xyz[:, 0] *= scale_xyz[0]
    xyz[:, 1] *= scale_xyz[1]
    xyz[:, 2] *= scale_xyz[2]

    return xyz, {
        "input_rows": len(df),
        "valid_xyz_rows": len(xyz),
        "x_column": x_col,
        "y_column": y_col,
        "z_column": z_col,
    }


def safe_to_csv(df, path, index=False):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        df.to_csv(path, index=index)
        return path
    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        df.to_csv(fallback, index=index)
        print(f"  Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback


def safe_to_excel(df, path, index=False, sheet_name="Sheet1"):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if not WRITE_EXCEL:
        return None

    try:
        df.to_excel(path, index=index, sheet_name=sheet_name)
        return path
    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        df.to_excel(fallback, index=index, sheet_name=sheet_name)
        print(f"  Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback
    except Exception as e:
        print(f"  Could not write Excel file {path}: {e}")
        return None


def write_csv_and_excel(df, csv_path, excel_path=None, sheet_name="Sheet1", index=False):
    csv_actual = safe_to_csv(df, csv_path, index=index)

    excel_actual = None
    if excel_path is not None:
        excel_actual = safe_to_excel(df, excel_path, index=index, sheet_name=sheet_name)

    return csv_actual, excel_actual


# ==========================================================
# Colocalization calculation
# ==========================================================
def nearest_neighbor_table(source_xyz, target_xyz, source_name, target_name):
    """
    For every source punctum, find the nearest punctum in the target channel.
    """
    if len(source_xyz) == 0:
        return pd.DataFrame(
            columns=[
                f"{source_name}_index",
                f"{source_name}_x",
                f"{source_name}_y",
                f"{source_name}_z",
                f"nearest_{target_name}_index",
                f"nearest_{target_name}_x",
                f"nearest_{target_name}_y",
                f"nearest_{target_name}_z",
                f"nearest_{target_name}_distance_um",
                "colocalized",
            ]
        )

    if len(target_xyz) == 0:
        out = pd.DataFrame(
            {
                f"{source_name}_index": np.arange(len(source_xyz)),
                f"{source_name}_x": source_xyz[:, 0],
                f"{source_name}_y": source_xyz[:, 1],
                f"{source_name}_z": source_xyz[:, 2],
                f"nearest_{target_name}_index": -1,
                f"nearest_{target_name}_x": np.nan,
                f"nearest_{target_name}_y": np.nan,
                f"nearest_{target_name}_z": np.nan,
                f"nearest_{target_name}_distance_um": np.nan,
                "colocalized": False,
            }
        )
        return out

    tree = cKDTree(target_xyz)
    distances, target_indices = tree.query(source_xyz, k=1)
    target_nearest_xyz = target_xyz[target_indices]

    out = pd.DataFrame(
        {
            f"{source_name}_index": np.arange(len(source_xyz)),
            f"{source_name}_x": source_xyz[:, 0],
            f"{source_name}_y": source_xyz[:, 1],
            f"{source_name}_z": source_xyz[:, 2],
            f"nearest_{target_name}_index": target_indices.astype(int),
            f"nearest_{target_name}_x": target_nearest_xyz[:, 0],
            f"nearest_{target_name}_y": target_nearest_xyz[:, 1],
            f"nearest_{target_name}_z": target_nearest_xyz[:, 2],
            f"nearest_{target_name}_distance_um": distances.astype(float),
            "colocalized": distances <= COLOCALIZATION_DISTANCE_UM,
        }
    )

    return out


def all_pairs_within_threshold(a_xyz, b_xyz, a_name, b_name):
    """
    Return every A-B punctum pair whose 3D distance is <= threshold.

    This can contain more rows than the number of A puncta because one A punctum
    can overlap with multiple B puncta, and vice versa.
    """
    if len(a_xyz) == 0 or len(b_xyz) == 0:
        return pd.DataFrame(
            columns=[
                f"{a_name}_index",
                f"{a_name}_x",
                f"{a_name}_y",
                f"{a_name}_z",
                f"{b_name}_index",
                f"{b_name}_x",
                f"{b_name}_y",
                f"{b_name}_z",
                "pair_distance_um",
            ]
        )

    a_tree = cKDTree(a_xyz)
    b_tree = cKDTree(b_xyz)

    neighbor_lists = a_tree.query_ball_tree(b_tree, r=COLOCALIZATION_DISTANCE_UM)

    rows = []
    for a_idx, b_indices in enumerate(neighbor_lists):
        for b_idx in b_indices:
            d = float(np.linalg.norm(a_xyz[a_idx] - b_xyz[b_idx]))
            rows.append(
                {
                    f"{a_name}_index": int(a_idx),
                    f"{a_name}_x": float(a_xyz[a_idx, 0]),
                    f"{a_name}_y": float(a_xyz[a_idx, 1]),
                    f"{a_name}_z": float(a_xyz[a_idx, 2]),
                    f"{b_name}_index": int(b_idx),
                    f"{b_name}_x": float(b_xyz[b_idx, 0]),
                    f"{b_name}_y": float(b_xyz[b_idx, 1]),
                    f"{b_name}_z": float(b_xyz[b_idx, 2]),
                    "pair_distance_um": d,
                }
            )

    return pd.DataFrame(rows)


def summarize_cell(series_label, series_folder, cell_i, a_file, b_file, a_xyz, b_xyz, a_to_b, b_to_a, pairs):
    a_count = len(a_xyz)
    b_count = len(b_xyz)

    a_coloc_count = int(a_to_b["colocalized"].sum()) if len(a_to_b) > 0 else 0
    b_coloc_count = int(b_to_a["colocalized"].sum()) if len(b_to_a) > 0 else 0

    unique_a_in_pairs = (
        int(pairs[f"{MRNA_A}_index"].nunique()) if len(pairs) > 0 else 0
    )
    unique_b_in_pairs = (
        int(pairs[f"{MRNA_B}_index"].nunique()) if len(pairs) > 0 else 0
    )

    a_nearest_col = f"nearest_{MRNA_B}_distance_um"
    b_nearest_col = f"nearest_{MRNA_A}_distance_um"

    a_dist = a_to_b[a_nearest_col].to_numpy(dtype=float) if len(a_to_b) > 0 else np.array([])
    b_dist = b_to_a[b_nearest_col].to_numpy(dtype=float) if len(b_to_a) > 0 else np.array([])

    a_dist = a_dist[np.isfinite(a_dist)]
    b_dist = b_dist[np.isfinite(b_dist)]

    pair_dist = pairs["pair_distance_um"].to_numpy(dtype=float) if len(pairs) > 0 else np.array([])

    return {
        "series_label": series_label,
        "series_folder": str(series_folder),
        "cell_index": cell_i,
        "cell_label": cell_label(cell_i),
        "mRNA_A": MRNA_A,
        "mRNA_B": MRNA_B,
        "colocalization_distance_um": COLOCALIZATION_DISTANCE_UM,
        "A_file": str(a_file),
        "B_file": str(b_file),
        "A_count": a_count,
        "B_count": b_count,
        "A_colocalized_count_nearest_neighbor": a_coloc_count,
        "B_colocalized_count_nearest_neighbor": b_coloc_count,
        "A_percent_colocalized_nearest_neighbor": 100.0 * a_coloc_count / a_count if a_count > 0 else np.nan,
        "B_percent_colocalized_nearest_neighbor": 100.0 * b_coloc_count / b_count if b_count > 0 else np.nan,
        "pair_count_within_threshold": int(len(pairs)),
        "unique_A_puncta_in_any_pair": unique_a_in_pairs,
        "unique_B_puncta_in_any_pair": unique_b_in_pairs,
        "A_percent_in_any_pair": 100.0 * unique_a_in_pairs / a_count if a_count > 0 else np.nan,
        "B_percent_in_any_pair": 100.0 * unique_b_in_pairs / b_count if b_count > 0 else np.nan,
        "A_to_B_mean_nearest_distance_um": float(np.mean(a_dist)) if len(a_dist) > 0 else np.nan,
        "A_to_B_median_nearest_distance_um": float(np.median(a_dist)) if len(a_dist) > 0 else np.nan,
        "A_to_B_min_nearest_distance_um": float(np.min(a_dist)) if len(a_dist) > 0 else np.nan,
        "B_to_A_mean_nearest_distance_um": float(np.mean(b_dist)) if len(b_dist) > 0 else np.nan,
        "B_to_A_median_nearest_distance_um": float(np.median(b_dist)) if len(b_dist) > 0 else np.nan,
        "B_to_A_min_nearest_distance_um": float(np.min(b_dist)) if len(b_dist) > 0 else np.nan,
        "pair_mean_distance_um": float(np.mean(pair_dist)) if len(pair_dist) > 0 else np.nan,
        "pair_median_distance_um": float(np.median(pair_dist)) if len(pair_dist) > 0 else np.nan,
        "pair_min_distance_um": float(np.min(pair_dist)) if len(pair_dist) > 0 else np.nan,
    }


# ==========================================================
# Plotting
# ==========================================================
def plot_cell_xy(a_xyz, b_xyz, a_to_b, b_to_a, pairs, out_path, title):
    plt.figure(figsize=(8, 7), facecolor="white")

    # Default all puncta.
    if len(a_xyz) > 0:
        plt.scatter(
            a_xyz[:, 0],
            a_xyz[:, 1],
            s=22,
            alpha=0.45,
            label=f"{MRNA_A} all",
        )

    if len(b_xyz) > 0:
        plt.scatter(
            b_xyz[:, 0],
            b_xyz[:, 1],
            s=22,
            alpha=0.45,
            label=f"{MRNA_B} all",
        )

    # Highlight colocalized puncta.
    if len(a_to_b) > 0:
        a_coloc = a_to_b[a_to_b["colocalized"]]
        if len(a_coloc) > 0:
            plt.scatter(
                a_coloc[f"{MRNA_A}_x"],
                a_coloc[f"{MRNA_A}_y"],
                s=60,
                marker="o",
                facecolors="none",
                linewidths=1.5,
                label=f"{MRNA_A} within {COLOCALIZATION_DISTANCE_UM:g} um",
            )

    if len(b_to_a) > 0:
        b_coloc = b_to_a[b_to_a["colocalized"]]
        if len(b_coloc) > 0:
            plt.scatter(
                b_coloc[f"{MRNA_B}_x"],
                b_coloc[f"{MRNA_B}_y"],
                s=60,
                marker="s",
                facecolors="none",
                linewidths=1.5,
                label=f"{MRNA_B} within {COLOCALIZATION_DISTANCE_UM:g} um",
            )

    # Draw thin pair links in xy projection.
    if len(pairs) > 0:
        max_lines = min(len(pairs), 200)
        for _, row in pairs.head(max_lines).iterrows():
            plt.plot(
                [row[f"{MRNA_A}_x"], row[f"{MRNA_B}_x"]],
                [row[f"{MRNA_A}_y"], row[f"{MRNA_B}_y"]],
                linewidth=0.5,
                alpha=0.35,
            )

    plt.xlabel("x (um)")
    plt.ylabel("y (um)")
    plt.title(title)
    plt.axis("equal")
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor="white", bbox_inches="tight")
    plt.close()


def plot_histogram(values, out_path, title, xlabel, bins=50):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if len(values) == 0:
        note_path = Path(out_path).with_suffix(".txt")
        note_path.write_text(
            f"No finite values available for plot:\n{title}\n",
            encoding="utf-8",
        )
        return

    plt.figure(figsize=(8, 6), facecolor="white")
    plt.hist(values, bins=bins, edgecolor="black")
    plt.xlabel(xlabel)
    plt.ylabel("Count")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor="white", bbox_inches="tight")
    plt.close()


def plot_cell_percent_summary(summary_df, out_path):
    if len(summary_df) == 0:
        return

    df = summary_df.copy()
    df["cell_id"] = df["series_label"].astype(str) + "_" + df["cell_label"].astype(str)

    plt.figure(figsize=(max(10, 0.35 * len(df)), 6), facecolor="white")

    x = np.arange(len(df))
    width = 0.42

    plt.bar(
        x - width / 2,
        df["A_percent_colocalized_nearest_neighbor"],
        width=width,
        label=f"{MRNA_A} near {MRNA_B}",
    )
    plt.bar(
        x + width / 2,
        df["B_percent_colocalized_nearest_neighbor"],
        width=width,
        label=f"{MRNA_B} near {MRNA_A}",
    )

    plt.xticks(x, df["cell_id"], rotation=90, fontsize=7)
    plt.ylabel("Percent colocalized")
    plt.title(f"Per-cell mRNA colocalization within {COLOCALIZATION_DISTANCE_UM:g} um")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor="white", bbox_inches="tight")
    plt.close()


# ==========================================================
# Workbook writing
# ==========================================================
def write_multi_sheet_workbook(path, sheet_to_df):
    if not WRITE_EXCEL:
        return None

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            for sheet_name, df in sheet_to_df.items():
                safe_sheet = str(sheet_name)[:31]
                df.to_excel(writer, sheet_name=safe_sheet, index=False)
        return path

    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        with pd.ExcelWriter(fallback, engine="openpyxl") as writer:
            for sheet_name, df in sheet_to_df.items():
                safe_sheet = str(sheet_name)[:31]
                df.to_excel(writer, sheet_name=safe_sheet, index=False)
        print(f"Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback

    except Exception as e:
        print(f"Could not write workbook {path}: {e}")
        return None


# ==========================================================
# Main analysis
# ==========================================================
def index_coordinate_files_by_mrna_and_cell(series_folder):
    coord_files = find_coordinate_files(series_folder)

    index = {}
    duplicates = []

    for p in coord_files:
        mrna = infer_mrna_from_path(p, series_folder=series_folder)
        cell_i = extract_cell_index(p.name)

        if mrna == "unknown" or cell_i is None:
            continue

        key = (mrna.upper(), cell_i)

        if key in index:
            duplicates.append(
                {
                    "series_folder": str(series_folder),
                    "mRNA": mrna,
                    "cell_index": cell_i,
                    "kept_file": str(index[key]),
                    "duplicate_file": str(p),
                }
            )
            continue

        index[key] = p

    return index, duplicates, coord_files


def analyze_cell_pair(series_folder, series_label, cell_i, a_file, b_file, series_output_root):
    a_xyz, a_meta = load_coordinates(
        a_file,
        scale_xyz=(A_X_SCALE_UM, A_Y_SCALE_UM, A_Z_SCALE_UM),
    )
    b_xyz, b_meta = load_coordinates(
        b_file,
        scale_xyz=(B_X_SCALE_UM, B_Y_SCALE_UM, B_Z_SCALE_UM),
    )

    cell_out = series_output_root / cell_label(cell_i)
    cell_out.mkdir(parents=True, exist_ok=True)

    a_to_b = nearest_neighbor_table(a_xyz, b_xyz, MRNA_A, MRNA_B)
    b_to_a = nearest_neighbor_table(b_xyz, a_xyz, MRNA_B, MRNA_A)
    pairs = all_pairs_within_threshold(a_xyz, b_xyz, MRNA_A, MRNA_B)

    # Add metadata columns.
    for df in [a_to_b, b_to_a, pairs]:
        df.insert(0, "series_label", series_label)
        df.insert(1, "series_folder", str(series_folder))
        df.insert(2, "cell_index", cell_i)
        df.insert(3, "cell_label", cell_label(cell_i))
        df.insert(4, "colocalization_distance_um", COLOCALIZATION_DISTANCE_UM)
        df.insert(5, "mRNA_A", MRNA_A)
        df.insert(6, "mRNA_B", MRNA_B)
        df.insert(7, "A_file", str(a_file))
        df.insert(8, "B_file", str(b_file))

    summary = summarize_cell(
        series_label=series_label,
        series_folder=series_folder,
        cell_i=cell_i,
        a_file=a_file,
        b_file=b_file,
        a_xyz=a_xyz,
        b_xyz=b_xyz,
        a_to_b=a_to_b,
        b_to_a=b_to_a,
        pairs=pairs,
    )

    summary.update(
        {
            "A_input_rows": a_meta["input_rows"],
            "A_valid_xyz_rows": a_meta["valid_xyz_rows"],
            "A_x_column": a_meta["x_column"],
            "A_y_column": a_meta["y_column"],
            "A_z_column": a_meta["z_column"],
            "B_input_rows": b_meta["input_rows"],
            "B_valid_xyz_rows": b_meta["valid_xyz_rows"],
            "B_x_column": b_meta["x_column"],
            "B_y_column": b_meta["y_column"],
            "B_z_column": b_meta["z_column"],
        }
    )

    base = f"{cell_label(cell_i)}_{sanitize_name(MRNA_A)}_vs_{sanitize_name(MRNA_B)}"

    a_to_b_csv = cell_out / f"{base}_{MRNA_A}_nearest_{MRNA_B}.csv"
    a_to_b_xlsx = cell_out / f"{base}_{MRNA_A}_nearest_{MRNA_B}.xlsx"
    write_csv_and_excel(a_to_b, a_to_b_csv, a_to_b_xlsx, sheet_name=f"{MRNA_A}_nearest_{MRNA_B}"[:31])

    b_to_a_csv = cell_out / f"{base}_{MRNA_B}_nearest_{MRNA_A}.csv"
    b_to_a_xlsx = cell_out / f"{base}_{MRNA_B}_nearest_{MRNA_A}.xlsx"
    write_csv_and_excel(b_to_a, b_to_a_csv, b_to_a_xlsx, sheet_name=f"{MRNA_B}_nearest_{MRNA_A}"[:31])

    pairs_csv = cell_out / f"{base}_pairs_within_{distance_tag()}.csv"
    pairs_xlsx = cell_out / f"{base}_pairs_within_{distance_tag()}.xlsx"
    write_csv_and_excel(pairs, pairs_csv, pairs_xlsx, sheet_name="pairs_within_threshold")

    summary_df = pd.DataFrame([summary])
    summary_csv = cell_out / f"{base}_summary.csv"
    summary_xlsx = cell_out / f"{base}_summary.xlsx"
    write_csv_and_excel(summary_df, summary_csv, summary_xlsx, sheet_name="summary")

    if MAKE_PER_CELL_PLOTS:
        plot_path = cell_out / f"{base}_xy_colocalization.png"
        plot_cell_xy(
            a_xyz=a_xyz,
            b_xyz=b_xyz,
            a_to_b=a_to_b,
            b_to_a=b_to_a,
            pairs=pairs,
            out_path=plot_path,
            title=f"{series_label} {cell_label(cell_i)}: {MRNA_A} vs {MRNA_B} within {COLOCALIZATION_DISTANCE_UM:g} um",
        )
        summary["xy_colocalization_plot"] = str(plot_path)

    summary["A_to_B_csv"] = str(a_to_b_csv)
    summary["B_to_A_csv"] = str(b_to_a_csv)
    summary["pairs_csv"] = str(pairs_csv)
    summary["summary_csv"] = str(summary_csv)

    return a_to_b, b_to_a, pairs, summary


def main():
    if not parent_folder.exists():
        raise FileNotFoundError(f"Parent folder does not exist: {parent_folder}")

    safe_a = sanitize_name(MRNA_A)
    safe_b = sanitize_name(MRNA_B)

    output_root = (
        parent_folder
        / OUTPUT_ROOT_NAME
        / f"{safe_a}_vs_{safe_b}_within_{distance_tag()}"
    )
    output_root.mkdir(parents=True, exist_ok=True)

    print(f"Parent folder: {parent_folder}")
    print(f"Output folder: {output_root}")
    print(f"mRNA A: {MRNA_A}")
    print(f"mRNA B: {MRNA_B}")
    print(f"Colocalization distance: {COLOCALIZATION_DISTANCE_UM} um")
    print("Definition: a punctum is colocalized if its nearest punctum in the other channel is within the threshold.")

    series_folders = find_series_folders(parent_folder)

    print(f"\nFound {len(series_folders)} Series folder(s):")
    for s in series_folders:
        print(f"  {s}")

    all_a_to_b = []
    all_b_to_a = []
    all_pairs = []
    all_summary = []
    all_duplicates = []
    all_unmatched = []
    all_input_index_rows = []

    for series_folder in series_folders:
        series_label = make_series_label(series_folder, parent_folder)
        series_output_root = output_root / "per_series" / series_label
        series_output_root.mkdir(parents=True, exist_ok=True)

        print("\n" + "=" * 80)
        print(f"Processing Series: {series_folder}")

        coord_index, duplicates, coord_files = index_coordinate_files_by_mrna_and_cell(series_folder)
        all_duplicates.extend(duplicates)

        # Save coordinate-file index for debugging.
        index_rows = []
        for p in coord_files:
            row = {
                "series_label": series_label,
                "series_folder": str(series_folder),
                "mRNA": infer_mrna_from_path(p, series_folder=series_folder),
                "cell_index": extract_cell_index(p.name),
                "coordinate_file": str(p),
            }
            index_rows.append(row)
            all_input_index_rows.append(row)

        if len(index_rows) > 0:
            write_csv_and_excel(
                pd.DataFrame(index_rows),
                series_output_root / f"{series_label}_input_coordinate_index.csv",
                series_output_root / f"{series_label}_input_coordinate_index.xlsx",
                sheet_name="input_index",
            )

        a_cells = {
            cell_i
            for (mrna, cell_i), _ in coord_index.items()
            if mrna == MRNA_A.upper()
        }
        b_cells = {
            cell_i
            for (mrna, cell_i), _ in coord_index.items()
            if mrna == MRNA_B.upper()
        }

        common_cells = sorted(a_cells.intersection(b_cells))
        a_only = sorted(a_cells.difference(b_cells))
        b_only = sorted(b_cells.difference(a_cells))

        print(f"  {MRNA_A} cells found: {len(a_cells)}")
        print(f"  {MRNA_B} cells found: {len(b_cells)}")
        print(f"  Matched cells analyzed: {len(common_cells)}")
        print(f"  {MRNA_A}-only cells: {len(a_only)}")
        print(f"  {MRNA_B}-only cells: {len(b_only)}")

        for cell_i in a_only:
            all_unmatched.append(
                {
                    "series_label": series_label,
                    "series_folder": str(series_folder),
                    "cell_index": cell_i,
                    "cell_label": cell_label(cell_i),
                    "status": f"{MRNA_A}_file_found_but_{MRNA_B}_missing",
                    "A_file": str(coord_index.get((MRNA_A.upper(), cell_i), "")),
                    "B_file": "",
                }
            )

        for cell_i in b_only:
            all_unmatched.append(
                {
                    "series_label": series_label,
                    "series_folder": str(series_folder),
                    "cell_index": cell_i,
                    "cell_label": cell_label(cell_i),
                    "status": f"{MRNA_B}_file_found_but_{MRNA_A}_missing",
                    "A_file": "",
                    "B_file": str(coord_index.get((MRNA_B.upper(), cell_i), "")),
                }
            )

        for cell_i in common_cells:
            a_file = coord_index[(MRNA_A.upper(), cell_i)]
            b_file = coord_index[(MRNA_B.upper(), cell_i)]

            try:
                print(f"  Analyzing {cell_label(cell_i)}")
                a_to_b, b_to_a, pairs, summary = analyze_cell_pair(
                    series_folder=series_folder,
                    series_label=series_label,
                    cell_i=cell_i,
                    a_file=a_file,
                    b_file=b_file,
                    series_output_root=series_output_root,
                )

                all_a_to_b.append(a_to_b)
                all_b_to_a.append(b_to_a)
                all_pairs.append(pairs)
                all_summary.append(summary)

                print(
                    f"    {MRNA_A} puncta: {summary['A_count']}; "
                    f"{MRNA_B} puncta: {summary['B_count']}; "
                    f"{MRNA_A} coloc: {summary['A_colocalized_count_nearest_neighbor']}; "
                    f"{MRNA_B} coloc: {summary['B_colocalized_count_nearest_neighbor']}; "
                    f"pairs: {summary['pair_count_within_threshold']}"
                )

            except Exception as e:
                print(f"    Error in {cell_label(cell_i)}: {e}")
                all_unmatched.append(
                    {
                        "series_label": series_label,
                        "series_folder": str(series_folder),
                        "cell_index": cell_i,
                        "cell_label": cell_label(cell_i),
                        "status": f"error: {e}",
                        "A_file": str(a_file),
                        "B_file": str(b_file),
                    }
                )

    # Pooled outputs.
    print("\n" + "=" * 80)
    print("Saving pooled outputs...")

    if len(all_summary) > 0:
        summary_df = pd.DataFrame(all_summary)
    else:
        summary_df = pd.DataFrame()

    a_to_b_df = pd.concat(all_a_to_b, ignore_index=True) if len(all_a_to_b) > 0 else pd.DataFrame()
    b_to_a_df = pd.concat(all_b_to_a, ignore_index=True) if len(all_b_to_a) > 0 else pd.DataFrame()
    pairs_df = pd.concat(all_pairs, ignore_index=True) if len(all_pairs) > 0 else pd.DataFrame()

    unmatched_df = pd.DataFrame(all_unmatched)
    duplicates_df = pd.DataFrame(all_duplicates)
    input_index_df = pd.DataFrame(all_input_index_rows)

    settings_df = pd.DataFrame(
        [
            {
                "MRNA_A": MRNA_A,
                "MRNA_B": MRNA_B,
                "COLOCALIZATION_DISTANCE_UM": COLOCALIZATION_DISTANCE_UM,
                "PROCESS_ONLY_CONVERTED_COORDINATES": PROCESS_ONLY_CONVERTED_COORDINATES,
                "A_X_SCALE_UM": A_X_SCALE_UM,
                "A_Y_SCALE_UM": A_Y_SCALE_UM,
                "A_Z_SCALE_UM": A_Z_SCALE_UM,
                "B_X_SCALE_UM": B_X_SCALE_UM,
                "B_Y_SCALE_UM": B_Y_SCALE_UM,
                "B_Z_SCALE_UM": B_Z_SCALE_UM,
                "parent_folder": str(parent_folder),
                "output_folder": str(output_root),
            }
        ]
    )

    write_csv_and_excel(
        summary_df,
        output_root / "ALL_cell_colocalization_summary.csv",
        output_root / "ALL_cell_colocalization_summary.xlsx",
        sheet_name="cell_summary",
    )

    write_csv_and_excel(
        a_to_b_df,
        output_root / f"ALL_{safe_a}_nearest_{safe_b}.csv",
        output_root / f"ALL_{safe_a}_nearest_{safe_b}.xlsx",
        sheet_name=f"{safe_a}_nearest_{safe_b}"[:31],
    )

    write_csv_and_excel(
        b_to_a_df,
        output_root / f"ALL_{safe_b}_nearest_{safe_a}.csv",
        output_root / f"ALL_{safe_b}_nearest_{safe_a}.xlsx",
        sheet_name=f"{safe_b}_nearest_{safe_a}"[:31],
    )

    write_csv_and_excel(
        pairs_df,
        output_root / f"ALL_{safe_a}_{safe_b}_pairs_within_{distance_tag()}.csv",
        output_root / f"ALL_{safe_a}_{safe_b}_pairs_within_{distance_tag()}.xlsx",
        sheet_name="pairs_within_threshold",
    )

    write_csv_and_excel(
        unmatched_df,
        output_root / "ALL_unmatched_or_failed_cells.csv",
        output_root / "ALL_unmatched_or_failed_cells.xlsx",
        sheet_name="unmatched_failed",
    )

    write_csv_and_excel(
        duplicates_df,
        output_root / "ALL_duplicate_coordinate_files.csv",
        output_root / "ALL_duplicate_coordinate_files.xlsx",
        sheet_name="duplicates",
    )

    write_csv_and_excel(
        input_index_df,
        output_root / "ALL_input_coordinate_file_index.csv",
        output_root / "ALL_input_coordinate_file_index.xlsx",
        sheet_name="input_index",
    )

    write_csv_and_excel(
        settings_df,
        output_root / "RUN_SETTINGS.csv",
        output_root / "RUN_SETTINGS.xlsx",
        sheet_name="settings",
    )

    workbook_path = write_multi_sheet_workbook(
        output_root / f"ALL_{safe_a}_vs_{safe_b}_colocalization_workbook.xlsx",
        {
            "cell_summary": summary_df,
            f"{safe_a}_nearest_{safe_b}": a_to_b_df,
            f"{safe_b}_nearest_{safe_a}": b_to_a_df,
            "pairs_within_threshold": pairs_df,
            "unmatched_failed": unmatched_df,
            "duplicates": duplicates_df,
            "input_index": input_index_df,
            "settings": settings_df,
        },
    )

    # Pooled plots.
    if MAKE_POOLED_PLOTS and len(summary_df) > 0:
        plot_cell_percent_summary(
            summary_df,
            output_root / "ALL_percent_colocalized_by_cell.png",
        )

    if MAKE_POOLED_PLOTS and len(a_to_b_df) > 0:
        col = f"nearest_{MRNA_B}_distance_um"
        if col in a_to_b_df.columns:
            plot_histogram(
                a_to_b_df[col],
                output_root / f"ALL_{safe_a}_nearest_{safe_b}_distance_histogram.png",
                f"{MRNA_A} nearest {MRNA_B} distance",
                f"Distance from {MRNA_A} to nearest {MRNA_B} (um)",
                bins=50,
            )

    if MAKE_POOLED_PLOTS and len(b_to_a_df) > 0:
        col = f"nearest_{MRNA_A}_distance_um"
        if col in b_to_a_df.columns:
            plot_histogram(
                b_to_a_df[col],
                output_root / f"ALL_{safe_b}_nearest_{safe_a}_distance_histogram.png",
                f"{MRNA_B} nearest {MRNA_A} distance",
                f"Distance from {MRNA_B} to nearest {MRNA_A} (um)",
                bins=50,
            )

    if MAKE_POOLED_PLOTS and len(pairs_df) > 0:
        plot_histogram(
            pairs_df["pair_distance_um"],
            output_root / f"ALL_{safe_a}_{safe_b}_pair_distances_within_{distance_tag()}.png",
            f"{MRNA_A}-{MRNA_B} pair distances within {COLOCALIZATION_DISTANCE_UM:g} um",
            "Pair distance (um)",
            bins=50,
        )

    print("\nDone.")
    print(f"Cells successfully analyzed: {len(summary_df)}")
    print(f"Total {MRNA_A} puncta analyzed: {int(summary_df['A_count'].sum()) if len(summary_df) > 0 else 0}")
    print(f"Total {MRNA_B} puncta analyzed: {int(summary_df['B_count'].sum()) if len(summary_df) > 0 else 0}")
    print(f"Total pair overlaps within threshold: {len(pairs_df)}")
    print(f"Output folder: {output_root}")

    if workbook_path is not None:
        print(f"Main Excel workbook: {workbook_path}")


if __name__ == "__main__":
    main()
