import re
import tkinter as tk
from pathlib import Path
from tkinter import filedialog

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ==========================================================
# Recursive RNA intensity histogram analysis
# ==========================================================
# Purpose
# -------
# Select a parent folder, recursively find raw smallFISH
# spots_extractions files, extract RNA spot intensities, and plot:
#
#   1. Histograms for each Series
#   2. Histograms for each experimental condition
#   3. Optional histograms split by RNA channel / probe
#
# Example input file:
#   spots_extractions_MS2 + ATP2  (yWL333)-001_nd2 - ..._000.csv
#
# Expected intensity column:
#   intensity
#
# The script keeps the raw files unchanged.
# ==========================================================


# ==========================================================
# Folder picker
# ==========================================================
root = tk.Tk()
root.withdraw()

parent_folder = Path(
    filedialog.askdirectory(
        title="Select parent folder containing smallFISH spots_extractions files"
    )
)

print("User selected:", parent_folder)


# ==========================================================
# User settings
# ==========================================================
OUTPUT_FOLDER_NAME = "RNA_intensity_histograms"

# Raw smallFISH files usually contain "spots_extractions" in the filename.
RAW_SPOT_FILE_REQUIRED_SUBSTRING = "spots_extractions"

# Column containing spot intensity.
# Keep as None to auto-detect.
INTENSITY_COLUMN = None

# Candidate intensity-column names used when INTENSITY_COLUMN is None.
INTENSITY_COLUMN_CANDIDATES = [
    "intensity",
    "spot_intensity",
    "rna_intensity",
    "signal",
    "integrated_intensity",
    "mean_intensity",
    "max_intensity",
]

# Known RNA channel names to infer from folder paths and filenames.
KNOWN_RNA_CHANNELS = ["MS2", "ATP2", "ATP3", "TIM50", "Tim50"]

# Histogram settings.
HISTOGRAM_BINS = 50

# Use the same x-axis limits for all histograms.
# If both are None, each plot uses its own automatic limits.
INTENSITY_XMIN = None
INTENSITY_XMAX = None

# If True, also makes log10 intensity histograms.
MAKE_LOG10_HISTOGRAMS = True

# If True, saves Excel outputs in addition to CSV.
WRITE_EXCEL = True

# If True, existing output files are overwritten.
OVERWRITE_EXISTING = True

# Plot one histogram for each Series pooled across RNA channels.
MAKE_SERIES_POOLED_HISTOGRAMS = True

# Plot one histogram for each Series and RNA channel.
MAKE_SERIES_BY_CHANNEL_HISTOGRAMS = True

# Plot one histogram for each condition pooled across RNA channels.
MAKE_CONDITION_POOLED_HISTOGRAMS = True

# Plot one histogram for each condition and RNA channel.
MAKE_CONDITION_BY_CHANNEL_HISTOGRAMS = True

# Plot one overall histogram across everything under the selected parent.
MAKE_ALL_PARENT_HISTOGRAM = True

# Optional: remove very low or very high values before plotting/summarizing.
# Keep as None to include all finite intensities.
FILTER_MIN_INTENSITY = None
FILTER_MAX_INTENSITY = None

# Folders generated by prior scripts that should not be searched as raw input.
SKIP_FOLDER_KEYWORDS = [
    "__pycache__",
    ".ipynb_checkpoints",
    "converted_coordinates",
    "random_ms2_output",
    "random_atp2_output",
    "random_atp3_output",
    "random_tim50_output",
    "random_output",
    "plots",
    "pooled_real_vs_random_comparisons",
    "strain_probe_comparison",
    "mito_visualization_interactive",
    "mito_rna_surface_GLOBAL_CALIBRATION",
    "mito_rna_surface_global_calibration",
    "mrna_coloc_BY_SERIES",
    "mrna_coloc_by_series",
    "node_mrna_dist_BY_SERIES",
    "node_mrna_dist_by_series",
    OUTPUT_FOLDER_NAME.lower(),
]


# ==========================================================
# Utility functions
# ==========================================================
def sanitize_name(name):
    name = str(name).strip()

    if name == "":
        name = "unknown"

    for bad in ["\\", "/", ":", "*", "?", '"', "<", ">", "|"]:
        name = name.replace(bad, "_")

    name = re.sub(r"\s+", "_", name)
    return name


def is_inside_skipped_folder(path):
    lower_parts = [str(part).lower() for part in Path(path).parts]
    joined = "/".join(lower_parts)

    return any(keyword.lower() in joined for keyword in SKIP_FOLDER_KEYWORDS)


def safe_to_csv(df, path, index=False):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        if path.exists() and not OVERWRITE_EXISTING:
            print(f"  Skipping existing file: {path.name}")
            return path
        df.to_csv(path, index=index)
        return path

    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        df.to_csv(fallback, index=index)
        print(f"  Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback


def safe_to_excel(df, path, index=False, sheet_name="Sheet1"):
    if not WRITE_EXCEL:
        return None

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        if path.exists() and not OVERWRITE_EXISTING:
            print(f"  Skipping existing file: {path.name}")
            return path
        df.to_excel(path, index=index, sheet_name=sheet_name[:31])
        return path

    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")
        df.to_excel(fallback, index=index, sheet_name=sheet_name[:31])
        print(f"  Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback

    except Exception as e:
        print(f"  Could not write Excel file {path}: {e}")
        return None


def write_csv_and_excel(df, csv_path, xlsx_path=None, sheet_name="Sheet1", index=False):
    csv_out = safe_to_csv(df, csv_path, index=index)
    xlsx_out = None

    if xlsx_path is not None:
        xlsx_out = safe_to_excel(df, xlsx_path, index=index, sheet_name=sheet_name)

    return csv_out, xlsx_out


def find_raw_spot_files(parent):
    files = []

    for ext in ["*.csv", "*.xlsx", "*.xlsm", "*.xls"]:
        files.extend(Path(parent).rglob(ext))

    out = []

    for p in sorted(set(files)):
        if not p.is_file():
            continue

        if p.name.startswith("~$"):
            continue

        if is_inside_skipped_folder(p):
            continue

        if RAW_SPOT_FILE_REQUIRED_SUBSTRING.lower() not in p.name.lower():
            continue

        lower_name = p.name.lower()

        generated_terms = [
            "summary",
            "spot_counts",
            "nn_distance",
            "random",
            "converted",
            "colocalization",
            "surface_distances",
            "nearest_node",
            "histogram",
            "distribution",
        ]

        if any(term in lower_name for term in generated_terms):
            continue

        out.append(p)

    return out


def read_spot_table(path):
    path = Path(path)
    suffix = path.suffix.lower()

    if suffix == ".csv":
        # smallFISH output is often semicolon-delimited.
        attempts = [
            {"sep": ";"},
            {"sep": ","},
            {"sep": "\t"},
            {"sep": None, "engine": "python"},
        ]

        best = None
        best_cols = -1

        for kwargs in attempts:
            try:
                df = pd.read_csv(path, **kwargs)
                df.columns = [str(c).strip() for c in df.columns]

                if df.shape[1] > best_cols:
                    best = df
                    best_cols = df.shape[1]

                try:
                    find_intensity_column(df)
                    return df
                except Exception:
                    pass

            except Exception:
                pass

        if best is not None:
            return best

        raise ValueError(f"Could not read CSV file: {path}")

    if suffix in [".xlsx", ".xlsm", ".xls"]:
        df = pd.read_excel(path)
        df.columns = [str(c).strip() for c in df.columns]
        return df

    raise ValueError(f"Unsupported file type: {path}")


def normalize_column_name(col):
    s = str(col).strip().lower()
    s = s.replace("µ", "u")
    s = s.replace("μ", "u")
    s = re.sub(r"[^a-z0-9]+", "", s)
    return s


def find_intensity_column(df):
    if INTENSITY_COLUMN is not None:
        if INTENSITY_COLUMN in df.columns:
            return INTENSITY_COLUMN

        raise ValueError(
            f"INTENSITY_COLUMN='{INTENSITY_COLUMN}' was not found. "
            f"Available columns: {list(df.columns)}"
        )

    normalized = {col: normalize_column_name(col) for col in df.columns}
    candidate_norms = {normalize_column_name(c) for c in INTENSITY_COLUMN_CANDIDATES}

    for col, norm in normalized.items():
        if norm in candidate_norms:
            return col

    # Fallback: any column containing "intensity".
    for col, norm in normalized.items():
        if "intensity" in norm:
            return col

    raise ValueError(
        "Could not identify an intensity column. "
        f"Available columns: {list(df.columns)}"
    )


def extract_cell_index(path_or_name):
    stem = Path(str(path_or_name)).stem

    # Typical smallFISH output: spots_extractions_..._000.csv
    m = re.search(r"[_\-](\d{1,4})$", stem)
    if m:
        return int(m.group(1))

    # Fallback: cell_000 style.
    m = re.search(r"(?:^|[_\-])cell[_\-]?(\d{1,4})(?:[_\-]|$)", stem, flags=re.IGNORECASE)
    if m:
        return int(m.group(1))

    return None


def find_series_folder(path):
    p = Path(path)

    for parent in [p.parent] + list(p.parents):
        if parent.name.lower().startswith("series"):
            return parent

    return None


def infer_condition_label(path, parent_folder, series_folder):
    """
    Experimental condition label.

    If selected parent contains:
      yWL333/MS2(ATP3)/Series 4/...
    condition label becomes:
      yWL333__MS2(ATP3)

    If selected parent is itself the condition folder and contains:
      Series 4/...
    condition label becomes selected parent folder name.
    """
    path = Path(path)
    parent_folder = Path(parent_folder)

    if series_folder is None:
        try:
            rel_parts = path.relative_to(parent_folder).parts
            if len(rel_parts) > 0:
                return sanitize_name(rel_parts[0])
        except Exception:
            pass

        return sanitize_name(parent_folder.name)

    try:
        rel_series = Path(series_folder).relative_to(parent_folder)
        before_series = list(rel_series.parts[:-1])

        if len(before_series) == 0:
            return sanitize_name(parent_folder.name)

        return sanitize_name("__".join(before_series))

    except Exception:
        return sanitize_name(parent_folder.name)


def infer_series_label(series_folder, parent_folder):
    if series_folder is None:
        return "unknown_series"

    try:
        rel = Path(series_folder).relative_to(parent_folder)
        return sanitize_name("__".join(rel.parts))
    except Exception:
        return sanitize_name(Path(series_folder).name)


def path_part_matches_channel(part, channel):
    p = str(part).strip().upper()
    c = str(channel).strip().upper()

    if p == c:
        return True

    if p.startswith(c + "_") or p.startswith(c + " ") or p.startswith(c + "-"):
        return True

    if re.search(rf"(^|[_\-\s\(\+]){re.escape(c)}([_\-\s\)\+]|$)", p):
        return True

    return False


def infer_rna_channel(path, series_folder=None):
    p = Path(path)

    # Prefer folders between the Series folder and spots_extraction.
    if series_folder is not None:
        try:
            rel_parts = p.relative_to(series_folder).parts

            useful_parts = []
            for part in rel_parts:
                useful_parts.append(part)
                if str(part).lower() == "spots_extraction":
                    break

            for part in useful_parts:
                for channel in KNOWN_RNA_CHANNELS:
                    if path_part_matches_channel(part, channel):
                        return channel.upper() if channel.upper() != "TIM50" else "TIM50"

        except Exception:
            pass

    # Fallback to filename/path search.
    for part in list(p.parts)[::-1]:
        for channel in KNOWN_RNA_CHANNELS:
            if path_part_matches_channel(part, channel):
                return channel.upper() if channel.upper() != "TIM50" else "TIM50"

    return "unknown_RNA"


def load_intensity_rows(file_path):
    df = read_spot_table(file_path)
    intensity_col = find_intensity_column(df)

    values = pd.to_numeric(df[intensity_col], errors="coerce")
    values = values.replace([np.inf, -np.inf], np.nan).dropna()

    if FILTER_MIN_INTENSITY is not None:
        values = values[values >= FILTER_MIN_INTENSITY]

    if FILTER_MAX_INTENSITY is not None:
        values = values[values <= FILTER_MAX_INTENSITY]

    series_folder = find_series_folder(file_path)
    condition_label = infer_condition_label(file_path, parent_folder, series_folder)
    series_label = infer_series_label(series_folder, parent_folder)
    rna_channel = infer_rna_channel(file_path, series_folder=series_folder)
    cell_index = extract_cell_index(file_path.name)

    rows = []

    for spot_i, value in enumerate(values.to_numpy(dtype=float)):
        rows.append(
            {
                "condition_label": condition_label,
                "series_label": series_label,
                "series_folder": str(series_folder) if series_folder is not None else "",
                "rna_channel": rna_channel,
                "cell_index": cell_index,
                "source_file": str(file_path),
                "source_filename": file_path.name,
                "intensity_column": intensity_col,
                "spot_row_index_after_filtering": spot_i,
                "intensity": float(value),
            }
        )

    return rows, {
        "source_file": str(file_path),
        "source_filename": file_path.name,
        "condition_label": condition_label,
        "series_label": series_label,
        "rna_channel": rna_channel,
        "cell_index": cell_index,
        "intensity_column": intensity_col,
        "raw_rows": int(len(df)),
        "finite_intensity_rows_after_filtering": int(len(values)),
    }


def summarize_group(df, group_cols):
    rows = []

    for group_values, sub in df.groupby(group_cols, dropna=False):
        if not isinstance(group_values, tuple):
            group_values = (group_values,)

        intensities = pd.to_numeric(sub["intensity"], errors="coerce").dropna()

        row = dict(zip(group_cols, group_values))
        row.update(
            {
                "n_spots": int(len(intensities)),
                "n_cells": int(sub["cell_index"].nunique()),
                "n_files": int(sub["source_file"].nunique()),
                "mean_intensity": float(intensities.mean()) if len(intensities) > 0 else np.nan,
                "median_intensity": float(intensities.median()) if len(intensities) > 0 else np.nan,
                "std_intensity": float(intensities.std(ddof=1)) if len(intensities) > 1 else np.nan,
                "sem_intensity": float(intensities.std(ddof=1) / np.sqrt(len(intensities))) if len(intensities) > 1 else np.nan,
                "min_intensity": float(intensities.min()) if len(intensities) > 0 else np.nan,
                "q25_intensity": float(intensities.quantile(0.25)) if len(intensities) > 0 else np.nan,
                "q75_intensity": float(intensities.quantile(0.75)) if len(intensities) > 0 else np.nan,
                "max_intensity": float(intensities.max()) if len(intensities) > 0 else np.nan,
            }
        )

        rows.append(row)

    return pd.DataFrame(rows)


# ==========================================================
# Plotting
# ==========================================================
def get_hist_range(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    if len(values) == 0:
        return None

    if INTENSITY_XMIN is None and INTENSITY_XMAX is None:
        return None

    left = INTENSITY_XMIN if INTENSITY_XMIN is not None else float(np.min(values))
    right = INTENSITY_XMAX if INTENSITY_XMAX is not None else float(np.max(values))

    if left >= right:
        return None

    return (left, right)


def save_histogram(values, out_path, title, xlabel="RNA spot intensity"):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if len(values) == 0:
        note = out_path.with_suffix(".txt")
        note.write_text(f"No finite intensity values available for:\n{title}\n", encoding="utf-8")
        return note

    plt.figure(figsize=(8, 6), facecolor="white")
    plt.hist(values, bins=HISTOGRAM_BINS, range=get_hist_range(values), edgecolor="black")
    plt.xlabel(xlabel)
    plt.ylabel("RNA spot count")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=300, facecolor="white", bbox_inches="tight")
    plt.close()

    return out_path


def save_log10_histogram(values, out_path, title):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    values = values[values > 0]

    if len(values) == 0:
        note = Path(out_path).with_suffix(".txt")
        note.parent.mkdir(parents=True, exist_ok=True)
        note.write_text(f"No positive intensity values available for log10 plot:\n{title}\n", encoding="utf-8")
        return note

    log_values = np.log10(values)

    return save_histogram(
        log_values,
        out_path,
        title=title,
        xlabel="log10 RNA spot intensity",
    )


def save_group_histograms(df, group_cols, output_folder, filename_prefix):
    plot_rows = []

    for group_values, sub in df.groupby(group_cols, dropna=False):
        if not isinstance(group_values, tuple):
            group_values = (group_values,)

        group_dict = dict(zip(group_cols, group_values))

        label_parts = [f"{col}_{sanitize_name(val)}" for col, val in group_dict.items()]
        label = "__".join(label_parts)

        title_parts = [f"{col}: {val}" for col, val in group_dict.items()]
        title = " | ".join(title_parts)

        intensities = pd.to_numeric(sub["intensity"], errors="coerce").dropna().to_numpy(dtype=float)

        out_dir = Path(output_folder)
        out_dir.mkdir(parents=True, exist_ok=True)

        png_path = out_dir / f"{filename_prefix}__{label}.png"
        saved = save_histogram(
            intensities,
            png_path,
            title=f"RNA intensity histogram | {title}",
        )

        plot_row = dict(group_dict)
        plot_row.update(
            {
                "plot_type": "raw_intensity_histogram",
                "n_spots": int(len(intensities)),
                "plot_file": str(saved),
            }
        )
        plot_rows.append(plot_row)

        if MAKE_LOG10_HISTOGRAMS:
            log_png_path = out_dir / f"{filename_prefix}__{label}__log10.png"
            log_saved = save_log10_histogram(
                intensities,
                log_png_path,
                title=f"log10 RNA intensity histogram | {title}",
            )

            log_row = dict(group_dict)
            log_row.update(
                {
                    "plot_type": "log10_intensity_histogram",
                    "n_spots": int(np.sum(np.asarray(intensities) > 0)),
                    "plot_file": str(log_saved),
                }
            )
            plot_rows.append(log_row)

    return plot_rows


def write_multi_sheet_workbook(path, sheet_to_df):
    if not WRITE_EXCEL:
        return None

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        if path.exists() and not OVERWRITE_EXISTING:
            print(f"  Skipping existing workbook: {path.name}")
            return path

        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            for sheet_name, df in sheet_to_df.items():
                safe_sheet = str(sheet_name)[:31]
                df.to_excel(writer, sheet_name=safe_sheet, index=False)

        return path

    except PermissionError:
        from datetime import datetime

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        fallback = path.with_name(f"{path.stem}_{stamp}{path.suffix}")

        with pd.ExcelWriter(fallback, engine="openpyxl") as writer:
            for sheet_name, df in sheet_to_df.items():
                safe_sheet = str(sheet_name)[:31]
                df.to_excel(writer, sheet_name=safe_sheet, index=False)

        print(f"  Permission denied writing {path.name}; saved as {fallback.name}")
        return fallback

    except Exception as e:
        print(f"  Could not write workbook {path}: {e}")
        return None


# ==========================================================
# Main
# ==========================================================
def main():
    if not parent_folder.exists():
        raise FileNotFoundError(f"Selected parent folder does not exist: {parent_folder}")

    output_root = parent_folder / OUTPUT_FOLDER_NAME
    output_root.mkdir(parents=True, exist_ok=True)

    print(f"Output folder: {output_root}")

    raw_files = find_raw_spot_files(parent_folder)

    print(f"\nFound {len(raw_files)} raw spots_extractions file(s).")

    all_rows = []
    file_summary_rows = []
    rejected_rows = []

    for i, file_path in enumerate(raw_files, start=1):
        print(f"\n[{i}/{len(raw_files)}] {file_path}")

        try:
            rows, file_summary = load_intensity_rows(file_path)
            all_rows.extend(rows)
            file_summary["status"] = "processed"
            file_summary["message"] = ""
            file_summary_rows.append(file_summary)

            print(
                f"  Processed {file_summary['finite_intensity_rows_after_filtering']} intensity value(s); "
                f"channel={file_summary['rna_channel']}; "
                f"series={file_summary['series_label']}; "
                f"condition={file_summary['condition_label']}"
            )

        except Exception as e:
            print(f"  ERROR: {e}")
            rejected_rows.append(
                {
                    "source_file": str(file_path),
                    "source_filename": file_path.name,
                    "status": "error",
                    "message": str(e),
                }
            )

    all_intensity_df = pd.DataFrame(all_rows)
    file_summary_df = pd.DataFrame(file_summary_rows)
    rejected_df = pd.DataFrame(rejected_rows)

    settings_df = pd.DataFrame(
        [
            {
                "parent_folder": str(parent_folder),
                "output_folder": str(output_root),
                "RAW_SPOT_FILE_REQUIRED_SUBSTRING": RAW_SPOT_FILE_REQUIRED_SUBSTRING,
                "INTENSITY_COLUMN": INTENSITY_COLUMN if INTENSITY_COLUMN is not None else "auto-detect",
                "HISTOGRAM_BINS": HISTOGRAM_BINS,
                "INTENSITY_XMIN": INTENSITY_XMIN,
                "INTENSITY_XMAX": INTENSITY_XMAX,
                "MAKE_LOG10_HISTOGRAMS": MAKE_LOG10_HISTOGRAMS,
                "FILTER_MIN_INTENSITY": FILTER_MIN_INTENSITY,
                "FILTER_MAX_INTENSITY": FILTER_MAX_INTENSITY,
            }
        ]
    )

    if len(all_intensity_df) == 0:
        print("\nNo usable intensity values were found.")
        write_csv_and_excel(
            file_summary_df,
            output_root / "RNA_intensity_file_summary.csv",
            output_root / "RNA_intensity_file_summary.xlsx",
            sheet_name="file_summary",
        )
        write_csv_and_excel(
            rejected_df,
            output_root / "RNA_intensity_rejected_files.csv",
            output_root / "RNA_intensity_rejected_files.xlsx",
            sheet_name="rejected_files",
        )
        return

    # Summary tables.
    series_summary_df = summarize_group(
        all_intensity_df,
        ["condition_label", "series_label"],
    )

    series_channel_summary_df = summarize_group(
        all_intensity_df,
        ["condition_label", "series_label", "rna_channel"],
    )

    condition_summary_df = summarize_group(
        all_intensity_df,
        ["condition_label"],
    )

    condition_channel_summary_df = summarize_group(
        all_intensity_df,
        ["condition_label", "rna_channel"],
    )

    parent_channel_summary_df = summarize_group(
        all_intensity_df,
        ["rna_channel"],
    )

    # Save tables.
    write_csv_and_excel(
        all_intensity_df,
        output_root / "ALL_RNA_spot_intensities.csv",
        output_root / "ALL_RNA_spot_intensities.xlsx",
        sheet_name="all_intensities",
    )

    write_csv_and_excel(
        file_summary_df,
        output_root / "RNA_intensity_file_summary.csv",
        output_root / "RNA_intensity_file_summary.xlsx",
        sheet_name="file_summary",
    )

    write_csv_and_excel(
        series_summary_df,
        output_root / "RNA_intensity_summary_by_series.csv",
        output_root / "RNA_intensity_summary_by_series.xlsx",
        sheet_name="by_series",
    )

    write_csv_and_excel(
        series_channel_summary_df,
        output_root / "RNA_intensity_summary_by_series_and_channel.csv",
        output_root / "RNA_intensity_summary_by_series_and_channel.xlsx",
        sheet_name="series_channel",
    )

    write_csv_and_excel(
        condition_summary_df,
        output_root / "RNA_intensity_summary_by_condition.csv",
        output_root / "RNA_intensity_summary_by_condition.xlsx",
        sheet_name="by_condition",
    )

    write_csv_and_excel(
        condition_channel_summary_df,
        output_root / "RNA_intensity_summary_by_condition_and_channel.csv",
        output_root / "RNA_intensity_summary_by_condition_and_channel.xlsx",
        sheet_name="condition_channel",
    )

    write_csv_and_excel(
        parent_channel_summary_df,
        output_root / "RNA_intensity_summary_by_channel.csv",
        output_root / "RNA_intensity_summary_by_channel.xlsx",
        sheet_name="by_channel",
    )

    write_csv_and_excel(
        rejected_df,
        output_root / "RNA_intensity_rejected_files.csv",
        output_root / "RNA_intensity_rejected_files.xlsx",
        sheet_name="rejected_files",
    )

    write_csv_and_excel(
        settings_df,
        output_root / "RNA_intensity_RUN_SETTINGS.csv",
        output_root / "RNA_intensity_RUN_SETTINGS.xlsx",
        sheet_name="settings",
    )

    workbook_path = write_multi_sheet_workbook(
        output_root / "RNA_intensity_histogram_analysis_workbook.xlsx",
        {
            "all_intensities": all_intensity_df,
            "file_summary": file_summary_df,
            "series_summary": series_summary_df,
            "series_channel": series_channel_summary_df,
            "condition_summary": condition_summary_df,
            "condition_channel": condition_channel_summary_df,
            "channel_summary": parent_channel_summary_df,
            "rejected_files": rejected_df,
            "settings": settings_df,
        },
    )

    # Plot outputs.
    plot_rows = []

    if MAKE_ALL_PARENT_HISTOGRAM:
        parent_plot_dir = output_root / "plots" / "parent"
        parent_plot_dir.mkdir(parents=True, exist_ok=True)

        values = all_intensity_df["intensity"].to_numpy(dtype=float)

        parent_hist = save_histogram(
            values,
            parent_plot_dir / "ALL_PARENT_RNA_intensity_histogram.png",
            title=f"All RNA spot intensities under {parent_folder.name}",
        )

        plot_rows.append(
            {
                "plot_group": "parent",
                "plot_type": "raw_intensity_histogram",
                "condition_label": "ALL",
                "series_label": "ALL",
                "rna_channel": "ALL",
                "n_spots": int(len(values)),
                "plot_file": str(parent_hist),
            }
        )

        if MAKE_LOG10_HISTOGRAMS:
            parent_log_hist = save_log10_histogram(
                values,
                parent_plot_dir / "ALL_PARENT_RNA_intensity_histogram_log10.png",
                title=f"log10 all RNA spot intensities under {parent_folder.name}",
            )

            plot_rows.append(
                {
                    "plot_group": "parent",
                    "plot_type": "log10_intensity_histogram",
                    "condition_label": "ALL",
                    "series_label": "ALL",
                    "rna_channel": "ALL",
                    "n_spots": int(np.sum(np.asarray(values) > 0)),
                    "plot_file": str(parent_log_hist),
                }
            )

    if MAKE_SERIES_POOLED_HISTOGRAMS:
        rows = save_group_histograms(
            all_intensity_df,
            ["condition_label", "series_label"],
            output_root / "plots" / "by_series",
            "RNA_intensity_by_series",
        )
        for row in rows:
            row["plot_group"] = "series_pooled"
        plot_rows.extend(rows)

    if MAKE_SERIES_BY_CHANNEL_HISTOGRAMS:
        rows = save_group_histograms(
            all_intensity_df,
            ["condition_label", "series_label", "rna_channel"],
            output_root / "plots" / "by_series_and_channel",
            "RNA_intensity_by_series_and_channel",
        )
        for row in rows:
            row["plot_group"] = "series_by_channel"
        plot_rows.extend(rows)

    if MAKE_CONDITION_POOLED_HISTOGRAMS:
        rows = save_group_histograms(
            all_intensity_df,
            ["condition_label"],
            output_root / "plots" / "by_condition",
            "RNA_intensity_by_condition",
        )
        for row in rows:
            row["plot_group"] = "condition_pooled"
        plot_rows.extend(rows)

    if MAKE_CONDITION_BY_CHANNEL_HISTOGRAMS:
        rows = save_group_histograms(
            all_intensity_df,
            ["condition_label", "rna_channel"],
            output_root / "plots" / "by_condition_and_channel",
            "RNA_intensity_by_condition_and_channel",
        )
        for row in rows:
            row["plot_group"] = "condition_by_channel"
        plot_rows.extend(rows)

    plot_index_df = pd.DataFrame(plot_rows)

    write_csv_and_excel(
        plot_index_df,
        output_root / "RNA_intensity_plot_index.csv",
        output_root / "RNA_intensity_plot_index.xlsx",
        sheet_name="plot_index",
    )

    print("\nDone.")
    print(f"Raw spot files processed: {len(file_summary_df)}")
    print(f"Rejected/error files: {len(rejected_df)}")
    print(f"Total RNA spots analyzed: {len(all_intensity_df)}")
    print(f"Conditions found: {all_intensity_df['condition_label'].nunique()}")
    print(f"Series found: {all_intensity_df['series_label'].nunique()}")
    print(f"RNA channels found: {all_intensity_df['rna_channel'].nunique()}")
    print(f"Output folder: {output_root}")

    if workbook_path is not None:
        print(f"Main workbook: {workbook_path}")


if __name__ == "__main__":
    main()
